const jennyHolzerTruisms = [
  "a little knowledge can go a long way",
  "a lot of professionals are crackpots",
  "a man can't know what it is to be a mother",
  "a positive attitude means all the difference in the world",
  "a strong sense of duty imprisons you",
  "absolute submission can be a form of freedom",
  "action causes more trouble than thought",
  "ambition is just as dangerous as complacency",
  "ambivalence can ruin your life",
  "an elite is inevitable",
  "artificial desires are despoiling the earth",
  "awful punishment awaits really bad people",
  "bad intentions can yield good results",
  "being alone with yourself is increasingly unpopular",
  "being judgmental is a sign of life",
  "being sure of yourself means you're a fool",
  "believing in rebirth is the same as admitting defeat",
  "boredom makes you do crazy things",
  "calm is more conductive to creativity than is anxiety",
  "change is valuable when the oppressed become tyrants",
  "chasing the new is dangerous to society",
  "children are the most cruel of all",
  "class action is a nice idea with no substance",
  "crime against property is relatively unimportant",
  "decency is a relative thing",
  "dependence can be a meal ticket",
  "disgust is the appropriate response to most situations",
  "don't place too much trust in experts",
  "drama often obscures the real issues",
  "eating too much is criminal",
  "emotional responses are as valuable as intellectual responses",
  "enjoy yourself because you can't change anything anyway",
  "ensure that your life stays in flux",
  "every achievement requires a sacrifice",
  "everyone's work is equally important",
  "everything that's interesting is new",
  "exceptional people deserve special concessions",
  "expressing anger is necessary",
  "faithfulness is a social not a biological law",
  "fake or real indifference is a powerful personal weapon",
  "fathers often use too much force",
  "fear is the greatest incapacitator",
  "freedom is a luxury not a necessity",
  "go all out in romance and let the chips fall where they may",
  "government is a burden on the people",
  "grass roots agitation is the only hope",
  "guilt and self-laceration are indulgences",
  "hiding your emotions is despicable",
  "holding back protects your vital energies",
  "if you can't leave your mark give up",
  "if you have many desires your life will be interesting",
  "ignoring enemies is the best way to fight",
  "inheritance must be abolished",
  "it can be helpful to keep going no matter what",
  "it is heroic to try to stop time",
  "it is man's fate to outsmart himself",
  "it is a gift to the world not to have babies",
  "it's better to be a good person than a famous person",
  "it's better to be naive than jaded",
  "it's good to give extra money to charity",
  "it's important to stay clean on all levels",
  "it's not good to operate on credit",
  "it's vital to live in harmony with nature",
  "just believing something can make it happen",
  "killing is unavoidable but nothing to be proud of",
  "knowledge should be advanced at all costs",
  "labor is a life-destroying activity",
  "lack of charisma can be fatal",
  "listen when your body talks",
  "looking back is the first sign of aging and decay",
  "loving animals is a substitute activity",
  "manual labor can be refreshing and wholesome",
  "men are not monogamous by nature",
  "moderation kills the spirit",
  "money creates taste",
  "morals are for little people",
  "most people are not fit to rule themselves",
  "mostly you should mind your own business",
  "much was decided before you were born",
  "myth can make reality more intelligible",
  "noise can be hostile",
  "nothing upsets the balance of good and evil",
  "offer very little information about yourself",
  "often you should act like you are sexless",
  "old friends are better left in the past",
  "pain can be a very positive thing",
  "people are boring unless they are extremists",
  "people are nuts if they think they are important",
  "people who don't work with their hands are parasites",
  "people who go crazy are too sensitive",
  "physical culture is second best",
  "planning for the future is escapism",
  "private property created crime",
  "religion causes as many problems as it solves",
  "remember you always have freedom of choice",
  "revolution begins with changes in the individual",
  "romantic love was invented to manipulate women",
  "salvation can't be bought and sold",
  "self-awareness can be crippling",
  "selfishness is the most basic motivation",
  "sloppy thinking gets worse over time",
  "starvation is nature's way",
  "stupid people shouldn't breed",
  "talking is used to hide one's inability to act",
  "the idea of revolution is an adolescent fantasy",
  "the only way to be pure is to stay by yourself",
  "the sum of your actions determines what you are",
  "there's nothing redeeming in toil",
  "thinking too much can only cause problems",
  "unique things must be the most valuable",
  "we must make sacrifices to maintain our quality of life",
  "when something terrible happens people wake up",
  "wishing things away is not effective",
  "worrying can help you prepare",
  "you are a victim of the rules you live by",
  "you are guileless in your dreams",
  "you can't expect people to be something they're not",
  "you can't fool others if you're fooling yourself",
  "you have to hurt others to be extraordinary",
  "you must disagree with authority figures",
  "your actions ae pointless if no one notices"
]

export default jennyHolzerTruisms;
